FROM ubuntu:jammy
LABEL maintainer="ivanov_mv@viro.edu.ru"
RUN apt update
RUN ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN apt -yq install tzdata
RUN apt -y install ntp
CMD ["service", "ntp", "start"]